mvdm/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views


app_name = 'mvdm'
urlpatterns = [
    path('',views.index,name='index'),
    path('product/<int:id>/',views.detail,name='detail'),
    path('createproduct/',views.create_product,name='createproduct'),
    path('editproduct/<int:id>/', views.product_edit, name='editproduct'),
    path('delete/<int:id>/', views.product_delete, name='delete'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('register/',views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='mvdm/logout.html'),name='logout'),
    path('invalid/', views.invalid, name='invalid'),
    path('purchases/', views.my_purchases, name='purchases'),
    path('sales/', views.sales, name='sales'),
    path('order/',views.order, name='order'),

]

mysite/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mvdm.urls')), 
]
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mvdm/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):

    def __str__(self):
        return self.name

    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    price = models.FloatField()
    file = models.FileField(upload_to='uploads')
    total_sales_amount = models.IntegerField(default=0)
    total_sales = models.IntegerField(default=0)


class OrderDetail(models.Model):

    def __str__(self):
        return self.customer_name

    customer_name = models.CharField(max_length=200)
    customer_email = models.EmailField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()
    has_paid = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

mvdm/forms.py
from django import forms
from .models import OrderDetail, Product
from django.contrib.auth.models import User

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name','description','price','file']


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = {'username', 'email', 'first_name'}

    def check_password(self):
        if self.cleaned_data['password']!= self.cleaned_data['password2']:
            raise forms.ValidationError('Passwords fields do not match')
        return self.cleaned_data['password2']


class LoginForm(forms.Form):
    username= forms.CharField()
    password= forms.CharField(widget=forms.PasswordInput)

class OrderForm(forms.ModelForm):
    class Meta:
        model = OrderDetail
        fields = ['customer_name', 'customer_email', 'product', 'amount', 'has_paid']

mvdm/views.py
from django.shortcuts import render, redirect
from .models import Product,OrderDetail
from .forms import  ProductForm, UserRegistrationForm, LoginForm
from django.db.models import Sum
import datetime
from django.contrib.auth import authenticate,login
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    products = Product.objects.all()

    # paginator code
    paginator = Paginator(products, 4)
    page = request.GET.get('page')
    products = paginator.get_page(page)

    return render(request,'mvdm/index.html',{'products':products})

def detail(request,id):
    product=Product.objects.get(id=id)
    return render(request, 'mvdm/detail.html',{'product':product})

def create_product(request):
    if request.method == 'POST':
        product_form = ProductForm(request.POST,request.FILES)
        if product_form.is_valid():
            new_product = product_form.save(commit=False)
            new_product.seller = request.user
            new_product.save()
            return redirect('mvdm:index')
    else:
        product_form = ProductForm()
    return render(request,'mvdm/create_product.html',{'product_form':product_form})

def product_edit(request,id):
    product = Product.objects.get(id=id)
    if product.seller != request.user:
        return redirect('mvdm:invalid')
    product_form = ProductForm(request.POST or None,request.FILES or None, instance=product)
    if request.method == 'POST':
        if product_form.is_valid():
            product_form.save()
            return redirect('mvdm:index')
    return render(request, 'mvdm/product_edit.html',{'product_form':product_form,'product':product})

def product_delete(request,id):
    product = Product.objects.get(id=id)
    if product.seller != request.user:
        return redirect('mvdm:invalid')
    if request.method == 'POST':
        product.delete()
        return redirect('mvdm:index')
    return render(request, 'mvdm/delete.html',{'product':product})

def dashboard(request):
    products = Product.objects.filter(seller=request.user)
    return render(request,'mvdm/dashboard.html', {'products':products})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            username = user_form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account is created')
            return redirect('mvdm:login')
    else:
        user_form = UserRegistrationForm()
    return render(request,'mvdm/register.html',{'user_form':user_form})

def login_view(request):
    if request.method == 'POST':
        form=LoginForm(request.POST) 
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(request,username=data['username'], password=data['password'])
            if user is not None:
                login(request,user)
                return redirect('mvdm:index')
            else:
                return HttpResponse("Invalid credentials")
    else:
        form = LoginForm()
        return render(request,'mvdm/login.html',{'form':form})


def invalid(request):
    return render(request, 'mvdm/invalid.html')

def my_purchases(request):
    orders = OrderDetail.objects.filter(customer_email= request.user.email)

    return render(request, 'mvdm/purchases.html',{'orders':orders})


def sales(request):
    orders = OrderDetail.objects.filter(product__seller=request.user)
    total_sales = orders.aggregate(Sum('amount'))
    print(total_sales)

    # 365 days sales sum
    last_year = datetime.date.today()- datetime.timedelta(days=365)
    data = OrderDetail.objects.filter(product__seller=request.user, created_on__gt = last_year)
    yearly_sales = data.aggregate(Sum('amount'))

    # 30 days sales sum
    last_month = datetime.date.today()- datetime.timedelta(days=30)
    data = OrderDetail.objects.filter(product__seller=request.user, created_on__gt = last_month)
    monthly_sales = data.aggregate(Sum('amount'))

    # 7 days sales sum
    last_weak = datetime.date.today()- datetime.timedelta(days=2)
    data = OrderDetail.objects.filter(product__seller=request.user, created_on__gt = last_weak)
    weakly_sales = data.aggregate(Sum('amount'))

    # everyday sum for the past 30 days
    daily_sales_sums = OrderDetail.objects.filter(product__seller= request.user).values('created_on__date').order_by('created_on__date').annotate(sum=Sum('amount'))
    print(daily_sales_sums)

    product_sales_sums = OrderDetail.objects.filter(product__seller= request.user).values('product__name').order_by('product__name').annotate(sum=Sum('amount'))
    print(product_sales_sums)


    return render(request ,'mvdm/sales.html',{'total_sales':total_sales,'yearly_sales':yearly_sales,'monthly_sales':monthly_sales,'weakly_sales':weakly_sales,'daily_sales_sums':daily_sales_sums,'product_sales_sums':product_sales_sums})




def order(request):
    orders = OrderDetail.objects.filter(product__seller=request.user)
    return render(request,'mvdm/order.html',{'orders':orders})

mvdm/templates/mvdm/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>Document</title>
</head>
<body>

    <nav class="shadow-lg bg-black text-white">
        <div class="flex flex-wrap justify-between ml-5 items-center mx-auto px-4 py-2.5">
            <!-- Website logo -->
            <a href="{% url 'mvdm:index' %}" class="flex items-center">
                <img class="h-9 mr-3" src="https://cdn0.iconfinder.com/data/icons/energy-free/32/Energy_Energy_Coal_Cart_Mining_Fuel-512.png">
                <span class="self-center text-xml font-semibold">Digital Marketplace</span>
            </a>
             <!-- Website items -->
            <div class="flex items-center">
                {% if request.user.is_authenticated %}
                <a href="{% url 'mvdm:dashboard' %}" class="mr-6 text-sm font-medium text-grey-500">Dashboard</a>
                <a href="{% url 'mvdm:sales' %}" class="mr-6 text-sm font-medium text-grey-500">Sales</a>
                <a href="{% url 'mvdm:order' %}" class="mr-6 text-sm font-medium text-grey-500">Orders</a>
                <a href="{% url 'mvdm:createproduct' %}" class="mr-6 text-sm font-medium text-grey-500">Create Products</a>
                <a href="{% url 'mvdm:purchases' %}" class="mr-6 text-sm font-medium text-grey-500">My Purchases</a>
                <a href="{% url 'mvdm:logout' %}" class="mr-6 text-sm font-medium text-grey-500">Logout</a>
                {% else %}
                <a href="{% url 'mvdm:login' %}" class="mr-6 text-sm font-medium text-grey-500">Log in</a>
                {% endif %}
                
                
            </div>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}">{{message}}</div>
            
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}
</body>
</html>

mvdm/templates/mvdm/create_product.html
{% extends 'mvdm/base.html' %}
{% block body %}
<h1 class="text-2xl font-semibold mt-"> 🎁Add Products </h1>
<div class="container py-5">
<form method="post" class="bg-white shadow-md m-10 w-2/5 rounded px-8 pt-6 pb-8 mb-4 font-semibold" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-2" >
                <label class="block text-sm font-bold mb-2" for="">Name</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10" >{{ product_form.name }}</div>
                <div></div>
        </div>
        <div class="mb-2" >
                <label class="block text-sm font-bold mb-2" for="">Description</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ product_form.description }}</div>
        </div>
        <div class="mb-2" >
            <label class="block text-sm font-bold mb-2" for="">Price</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ product_form.price }}</div>
        </div>
        <div class="mb-2" >
            <label class="block text-sm font-bold mb-2" for="">Upload File</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ product_form.file }}</div>
        </div>


        
        <button class="text-white bg-green-500 px-5 py-2 rounded m-2" type="submit">Add</button>
        
</form>
</div>
{% endblock %}

mvdm/templates/mvdm/dashboard.html
{% extends 'mvdm/base.html' %}
{% block body %}
    <div class="flex justify-between">
        <div class="ml-20 mt-10 font-bold text-xl">
            My Products
        </div>
        <div class="ml-20 mt-10">
            <a class="bg-green-500 text-white px-2 py-4 mr-10 rounded-lg" href="{% url 'mvdm:createproduct' %}">New Product</a>
        </div>
    </div>
    <div class="products-container p-10 m-5">
        {% for product in products %}
        <div class="flex shadow-lg m-5 p-2 justify-between">
            <div class="flex w-1/4">
                <img class="h-20" src="https://w7.pngwing.com/pngs/522/620/png-transparent-photo-image-person-icon-images-thumbnail.png">
                <div class="relative group">
                    <a href="{% url 'mvdm:editproduct' product.id %}">
                <div class="opacity-0 group-hover:opacity-100 duration-300 absolute inset-x-0 bottom-0 p-4 justify-center items-end bg-white font-semibold">Edit Product
                </div>
                <div class="ml-5">
                    <div class="font-bold text-sm">{{ product.name }}</div>
                    <div class="text-sm text-green-500">₹ {{product.price}}</div>
                </div>
                </a>
            </div>
            </div>
            <div>
                <div class="text-xl text-green-500" >₹ {{ product.total_sales_amount }}</div>
                <div class="text-sm">Total Earning</div>
            </div>
            <div>
                <div class="text-xl" >{{ product.total_sales }}</div>
                <div class="text-sm">Total orders</div>
            </div>
            <div class="pr-5">
                <div class="text-xl" >4.1</div>
                <div class="text-sm">Rating</div>
            </div>
        </div>

        {% endfor %}

    </div>

{% endblock %}

mvdm/templates/mvdm/delete.html
{% extends 'mvdm/base.html' %}
{% block body %}
<div class="flex flex-col justify-center items items-center min-h-screen">
    <h1 class="font-semibold">Are you sure you wnat to delete the product ?</h1>
    <form action="{% url 'mvdm:delete' product.id %}" method="post">
        {% csrf_token %}
        <button class="bg-red-500 text-white px-4 py-2 rounded m-2">Confirm</button>
        <a class="bg-green-500 text-white px-4 py-2 rounded m-2" href="{% url 'mvdm:index' %}">No</a>
    </form>
</div>

{% endblock %}

mvdm/templates/mvdm/detail.html
{% extends 'mvdm/base.html' %}
{% block body %}
    <div class="flex p-10">
        <div>
            <img src="https://w7.pngwing.com/pngs/522/620/png-transparent-photo-image-person-icon-images-thumbnail.png">  
        </div>
        <div class="pl-10">
            <div class="text-4xl mb-4">{{ product.name }}</div>
            <div class="md-4 ">{{ product.description }}</div>
            <div class="mb-4 text-green-700 font-bold">₹ {{product.price}}</div>
            <div>
                <button id="checkout-button" class="bg-green-500 text-white px-4 py-2 rounded-lg">Buy</button>
            </div>
        </div>
    </div>
{% endblock %}

mvdm/templates/mvdm/index.html
{% extends 'mvdm/base.html' %}
{% block body %}
<div class="product-container flex m-5">
    {% for product in products %}
    <div class="product shadow-lg w-1/5 rounded-lg m-10 ">
        <div class="product-image">
            <img src="https://w7.pngwing.com/pngs/522/620/png-transparent-photo-image-person-icon-images-thumbnail.png">
        </div>
        <div class="p-5">
            <div class="font-bold">
                {{product.name}}
            </div>
            <div class="font-bold">
                {{product.description}}
            </div>
            <div class="font-bold">
               Created by: {{product.seller}}
            </div>
            <div class="font-bold text-green-700">
                ₹ {{product.price}}
            </div>
            <div class="mt-3">
                <a class="bg-green-500 text-whit px-4 py-2 rounded-lg" href="{% url 'mvdm:detail' product.id %}"><b>View Details</b></a>
            </div>
            
        </div>
    </div>   
{% endfor %}
</div>


<div class="row">
    <div class="flex items-center justify-center">
        <nav class="inline-flex space-x-2">
          {% if products.has_previous %}
            <a href="?page={{ products.previous_page_number }}" class="px-2 py-1 text-blue-500 rounded-md hover:bg-blue-500 hover:text-white">Previous</a>
          {% endif %}
      
          <a href="?page={{ products.number }}" class="px-2 py-1 text-white bg-blue-500 rounded-md">{{ products.number }}</a>
      
          {% if products.has_next %}
            <a href="?page={{ products.next_page_number }}" class="px-2 py-1 text-blue-500 rounded-md hover:bg-blue-500 hover:text-white">Next</a>
          {% endif %}
        </nav>
      </div>
      
  </div>


{% endblock %}


        

mvdm/templates/mvdm/invalid.html
{% extends 'mvdm/base.html' %}
{% block body %}

<div class="flex flex-col justify-center items-center min-h-screen">
    <h1 class="text-2xl text-red-500 font-semibold">Invalid Request</h1>
</div>
{% endblock %}

mvdm/templates/mvdm/login.html
{% extends 'mvdm/base.html' %}
{% block body %}

<div class="flex flex-col justify-center items-center min-h-screen">
    <h1 class="text-2xl font-semibold"> 🙍Login User</h1>
<form method="post" class="shadow-lg p-10">
        {% csrf_token %}
        <div class="mb-2" >
                <label class="block text-sm font-bold mb-2" for="">Username</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10" >{{ form.username }}</div>
                <div></div>
        </div>
        <div class="mb-2" >
                <label class="block text-sm font-bold mb-2" for="">Password</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ form.password }}</div>
        </div>

        
        <button class="text-white bg-green-500 px-5 py-2 rounded m-2" type="submit">Login</button>
</form>
<p class="m-10 " >New to the Website ?<span><a class="text-indigo-500" href="{% url 'mvdm:register'%}"> Click here</a></span> to register</p>
</div>
{% endblock %}

mvdm/templates/mvdm/logout.html
{% extends 'mvdm/base.html' %}
{% block body %}

<div class="flex flex-col justify-center items-center min-h-screen">
    <h1 class="text-2xl font-semibold">You have been logged out Succesfully</h1>
    <p><span><a class="text-indigo-500" href="{% url 'mvdm:login' %}">Click here</a> to log back in</span></p>
</div>
{% endblock %}

mvdm/templates/mvdm/order.html
{% extends 'mvdm/base.html' %}
{% block body %}

<div class="flex justify-between">
    <h1 class="ml-10 mt-10 font-bold text-2xl">🛒 Orders</h1>
</div>
<div class="flex justify-center">
    
        

        <div class="flex flex-wrap m-5">
            {% for order in orders %}
            <div class="w-1/3">
                <div class="shadow-lg p-5 m-5">
                    <div class="font-bold">Customer Name: {{ order.customer_name }}</div>
                    <div>Customer Email: {{ order.customer_email }}</div>
                    <div>Product: {{ order.product.name }}</div>
                    <div>Amount: {{ order.amount }}</div>
                    <div>Has Paid: {% if order.has_paid %} Yes {% else %} No {% endif %}</div>
                    <div>Created On: {{ order.created_on }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
</div>

{% endblock %}

mvdm/templates/mvdm/product_edit.html
{% extends 'mvdm/base.html' %}
{% block body %}

<div class="container py-5">
    <h1 class="text-2xl font-semibold">Edit Products </h1>
<form method="post" class="bg-white shadow-md m-10 w-2/5 rounded px-8 pt-6 pb-8 mb-4 font-semibold" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-2" >
                <label class="block text-sm font-bold mb-2" for="">Name</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10" >{{ product_form.name }}</div>
                <div></div>
        </div>
        <div class="mb-2" >
                <label class="block text-sm font-bold mb-2" for="">Description</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ product_form.description }}</div>
        </div>
        <div class="mb-2" >
            <label class="block text-sm font-bold mb-2" for="">Price</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ product_form.price }}</div>
        </div>
        <div class="mb-2" >
            <label class="block text-sm font-bold mb-2" for="">Upload File</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ product_form.file }}</div>
        </div>


        
        <button class="text-white bg-green-500 px-5 py-2 rounded m-2" type="submit">Update</button>

        <a class="text-white bg-red-500 px-5 py-2 rounded m-2" href="{% url 'mvdm:delete' product.id %}">Delete</a>
        
</form>

</div>
{% endblock %}

mvdm/templates/mvdm/purchases.html
{% extends 'mvdm/base.html' %}
{% block body %}
    <div class="flex justify-between">
        <div class="ml-20 mt-10 font-bold text-xl">
            My Purchases
        </div>
        <div class="ml-20 mt-10">
            <a class="bg-green-500 text-white px-2 py-4 mr-10 rounded-lg" href="{% url 'mvdm:createproduct' %}">New Product</a>
        </div>
    </div>
    <div class="products-container shadow-lg p-10 m-5">
        <div class="order-header flex m-5 p-2 font-bold">
            <div class="w-1/4">
                Product Name
            </div>
            <div class="w-1/4">
                Amount Piad
            </div>
            <div class="w-1/4">
                Order Date
            </div>
            <div class="w-1/4">
                Download Link
            </div>
        </div>
        {% for order in orders %}
        <div class="flex m-5 p-2">
            <div class="w-1/4">
                {{ order.product.name}}
            </div>
            <div class="w-1/4 text-green-500">
                ₹ {{ order.amount }}
            </div>
            <div class="w-1/4">
                {{ order.created_on }}
            </div>
            <div class="w-1/4">
                <a class="bg-green-500 text-white px-4 py-2 rounded m-2" href="{{ order.product.file.url }}" download>Click to download</a>
            </div>

        </div>

        {% endfor %}

    </div>

{% endblock %}

mvdm/templates/mvdm/register.html
{% extends 'mvdm/base.html' %}
{% block body %}
<div class="flex flex-col justify-center items-center min-h-screen">
    <h1 class="text-2xl font-semibold"> 🙍Register User</h1>
<form method="post" class="shadow-lg p-10">
        {% csrf_token %}
        <div class="mb-2" >
                <label class="block text-sm font-bold mb-2" for="">Username</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10" >{{ user_form.username }}</div>
        </div>
        <div class="mb-2" >
                <label class="block text-sm font-bold mb-2" for="">Email</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ user_form.email }}</div>
        </div>
        <div class="mb-2" >
            <label class="block text-sm font-bold mb-2" for="">First name</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ user_form.first_name }}</div>
        </div>
        <div class="mb-2" >
            <label class="block text-sm font-bold mb-2" for="">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ user_form.password }}</div>
        </div>
        <div class="mb-2" >
            <label class="block text-sm font-bold mb-2" for="">Confirm Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10">{{ user_form.password2 }}</div>
        </div>

        <button class="text-white bg-green-500 px-5 py-2 rounded m-2" type="submit">Register</button>
</form>
<p class="m-10 " >Already registered ?<span><a class="text-indigo-500" href="{% url 'mvdm:login' %}"> Click here</a></span> to log in</p>
</div>

{% endblock %}

mvdm/templates/mvdm/sales.html
{% extends 'mvdm/base.html' %}
{% block body %}

<div class="flex justify-between">
    <div class="ml-10 mt-10 font-bold text-xl">Sales Stats</div>
    <div class="mr-20 mt-10">
        <a class="bg-green-500 text-white px-2 py-4 rounded m-2" href="{% url 'mvdm:dashboard' %}">Dashboard</a>
    </div>
</div>
<div class="shadow-lg p-10 m-5">
    <div class="text-5xl font-bold">
        ₹ {{ total_sales.amount__sum }}
    </div>
    <div class="mt-10">
        Your Lifetime Revenue
    </div>
</div>
<div class="flex">
    <div class="p-5 w-1/3">
        <div class="shadow-lg p-10">
        <div class="text-4xl font-bold">₹ {{ yearly_sales.amount__sum }}</div>
        <div class="mt-4">Last 365 days</div>
    </div>
    </div>
    <div class="p-5 w-1/3">
        <div class="shadow-lg p-10">
        <div class="text-4xl font-bold">₹ {{ monthly_sales.amount__sum }}</div>
        <div class="mt-4">Last 30 days</div>
    </div>
    </div>
    <div class="p-5 w-1/3">
        <div class="shadow-lg p-10">
        <div class="text-4xl font-bold">₹ {{ weakly_sales.amount__sum }}</div>
        <div class="mt-4">Last 7 days</div>
    </div>
    </div>

</div>

<div class="flex">
    <div class="w-1/2 shadow-lg m-10" id="sales-table">
        <div class="text-xl font-bold ml-10 mt-10">30 Days Sales</div>
        <div class="flex m-10 mt-5 mb-5 font-semibold">
            <div class="w-1/2">
                Day
            </div>
            <div class="w-1/2">
                Total sales
            </div>
        </div>
        {% for daily_sales_sum in daily_sales_sums %}
        <div class="flex m-10 mt-5 mb-5">
            <div class="w-1/2 created-date">{{ daily_sales_sum.created_on__date }}</div>
            <span class="WebRupee text-green-500">&#x20B9;</span>&nbsp;
            <div class="w-1/2 font-bold text-green-500 day-sum">{{ daily_sales_sum.sum }}</div>
        </div>
        {% endfor %}
    </div>
    <div class="w-1/2 shadow-lg m-10">
        <div class="ml-10 mt-10 font-bold text-xl">30 day Sales</div>
            <canvas id="myChart"></canvas>
    </div>
</div>
<div class="flex">
    <div class="w-1/2 shadow-lg m-10">
        <div class="ml-10 mt-10 font-bold text-xl">Product Sales Distribution</div>
             <canvas id="myChart1"></canvas>
    </div>
    <div class="w-1/2 shadow-lg m-10">
        <div class="text-xl font-bold ml-10 mt-10">Product Sales</div>
        <div class="flex m-10 mt-5 mb-5 font-semibold">
            <div class="w-1/2">
                Product Name
            </div>
            <div class="w-1/2">
                Total sales
            </div>
        </div>
        {% for product_sales_sum in product_sales_sums %}
        <div class="flex m-10 mt-5 mb-5">
            <div class="w-1/2 product-name">{{ product_sales_sum.product__name }}</div>
            <span class="WebRupee text-green-500">&#x20B9;</span>&nbsp;
            <div class="w-1/2 font-bold text-green-500 product-sum">{{ product_sales_sum.sum }}</div>
        </div>
        {% endfor %}
    </div>
</div>

<script>

    const sums = document.getElementsByClassName('day-sum');
    const sum_values = [];
    for(let i=0; i<sums.length; i++) {
        single_sum = sums[i].innerText;
        sum_values.push(parseInt(single_sum));
    }
    console.log(sum_values);

    const dates = document.getElementsByClassName('created-date');
    const date_values =[];
    for(let i=0; i<dates.length; i++){
        single_date = dates[i].innerText;
        date_values.push(single_date);
    }
    console.log(date_values);

    const product_name = document.getElementsByClassName('product-name');
    const name_values =[];
    for(let i=0; i<product_name.length; i++){
        single_name = product_name[i].innerText;
        name_values.push(single_name);
    }
    console.log(name_values);

    const product_sum = document.getElementsByClassName('product-sum');
    const psum_values =[];
    for(let i=0; i<product_sum.length; i++){
        single_psum = product_sum[i].innerText;
        psum_values.push(single_psum);
    }
    console.log(psum_values);


    const ctx = document.getElementById('myChart');
  
    new Chart(ctx, {
      type: 'line',
      data: {
        labels: date_values,
        datasets: [{
          label:' Sales for the past 30 days',
          data: sum_values ,
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });



    const ctx1 = document.getElementById('myChart1');
  
    new Chart(ctx1, {
      type: 'bar',
      data: {
        labels: name_values,
        datasets: [{
          label:'Product Sales Sum',
          data:psum_values,
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  </script>
   
{% endblock %}